name: safarni
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  convex_bottom_bar: ^3.2.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  fan_carousel_image_slider: ^1.3.0
  flexi_productimage_slider: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  flutter_stripe: ^12.0.0
  flutter_svg: ^2.2.0
  get_it: ^8.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  image_picker: ^1.2.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.7.2
  shared_preferences: ^2.2.0

dev_dependencies:

  # Code Generation - Compatible versions
  build_runner: ^2.4.9
  flutter_assets: ^0.0.6
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: 2.0.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/
    - assets/images/gallery/
    - assets/fonts/
    - assets/icons/
    - assets/svgs/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"
  min_sdk_android: 21

flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/
  filename: app_assets.dart
